library(shiny)
library(DT)
library(RColorBrewer)
library(reticulate)
library(tiff)
library(png)

# Define any Python packages needed for the app here:
# (Make sure these are installed in your Python environment)
PYTHON_DEPENDENCIES = c('pip', 'numpy', 'matplotlib', 'scipy', 'scikit-image')

# Begin app server
shinyServer(function(input, output) {
  
  # ------------------ App virtualenv setup (Do not edit) ------------------- #
  virtualenv_create("py3-virtualenv", python = "/usr/bin/python3")
  use_virtualenv("py3-virtualenv", required = TRUE)
  for (pkg in PYTHON_DEPENDENCIES) {
    py_install(pkg, envname = "py3-virtualenv")
  }
  
  # ------------------ App server logic (Edit anything below) --------------- #
  # Import python functions to R
  reticulate::source_python('python_functions.py')
  
  # Image upload and conversion from TIFF to PNG
  observeEvent(input$upload, {
    output$img <- renderImage({
      # Ensure a file has been uploaded
      if (is.null(input$upload)) {
        return(NULL)
      }
      
      # Specify the path to the temporary file
      temp_file_path <- input$upload$datapath
      
      # Read the TIFF file at the temp path
      tiff_image <- readTIFF(temp_file_path, native = FALSE)
      
      # Convert the TIFF to PNG and save to a temp file
      png_filename <- tempfile(fileext = ".png")
      writePNG(tiff_image, target = png_filename)
      
      # Return the list required by renderImage to display the PNG
      list(src = png_filename, contentType = 'image/png', alt = "Uploaded Image")
    }, deleteFile = TRUE)  # Set deleteFile to TRUE to remove the temp file when done
  })
  
  # Placeholder for cells function or any other operation to handle file path input
  output$contents <- renderTable({
    # Trigger this reactive block when the user inputs a file path and clicks a button
    req(input$fp) # Require that input$fp is not NULL
    req(input$rp)
    
    # Call the Python function
    results_path <- py$cell(input$fp, input$rp)
    
    # Read the CSV file generated by Python{
    read.csv(results_path, stringsAsFactors = FALSE)
  })
  output$tbl <- renderDT(
    read.csv(input$rp)
  )
  output$message <- renderText({
    return(test_string_function(input$str))
  })
  
  # Test that numpy function can be used
  output$xy <- renderText({
    z = test_numpy_function(input$x, input$y)
    return(paste0('x + y = ', z))
  })
  
  # Display info about the system running the code
  output$sysinfo <- DT::renderDataTable({
    s = Sys.info()
    df = data.frame(Info_Field = names(s),
                    Current_System_Setting = as.character(s))
    return(datatable(df, rownames = F, selection = 'none',
                     style = 'bootstrap', filter = 'none', options = list(dom = 't')))
  })
  
  # Display system path to python
  output$which_python <- renderText({
    paste0('which python: ', Sys.which('python'))
  })
  
  # Display Python version
  output$python_version <- renderText({
    rr = reticulate::py_discover_config(use_environment = 'python35_env')
    paste0('Python version: ', rr$version)
  })
  
  # Display RETICULATE_PYTHON
  output$ret_env_var <- renderText({
    paste0('RETICULATE_PYTHON: ', Sys.getenv('RETICULATE_PYTHON'))
  })
  
  # Display virtualenv root
  output$venv_root <- renderText({
    paste0('virtualenv root: ', reticulate::virtualenv_root())
  })
  
})