library(shiny)
library(shinycssloaders)
library(DT)

# Begin UI for the R + reticulate example app
ui <- fluidPage(
  
  titlePanel('Example app: Using R Shiny + reticulate'),
  
  sidebarLayout(
    sidebarPanel(
      # Inputs to Python functions called by reticulate
      textInput('fp', 'Filepath to images', value = 'Enter the path to a image file'),
      textInput('rp', 'Filepath to results', value = 'Enter the path to a CSV file'),
      fileInput('upload', 'Upload image', accept = c('image/tiff', 'image/png')),
      numericInput('num', 'Number of files uploaded', value = 1),
      numericInput('x', 'x value', value = 1),
      numericInput('y', 'y value', value = 2)
    ),
    mainPanel(
      tabsetPanel(type = 'tabs',
                  tabPanel('Using R and Python functions', 
                           br(),
                           h3('The image uploaded in .png format'),
                           imageOutput("img", width = "50%", height = "50%"),
                           br(),
                           h3('Outputs generated by Python functions via reticulate'),
                           verbatimTextOutput('message'),
                           br(),
                           'Use the numpy Python package to add two numbers',
                           verbatimTextOutput('xy')
                  ),
                 tabPanel('Cell Analysis',
                          h3('Cell Analysis Results'),
                          actionButton('analyze_btn', 'Analyze Cells'),
                          DT::dataTableOutput('contents'), # Add this line to display the results
                          br(),
                          actionButton('show_btn', 'Show Results'),
                          DTOutput('tbl')
                 ),
                  tabPanel('Architecture Info', 
                           h3('Current architecture info'),
                           hr(),
                           shinycssloaders::withSpinner(DT::dataTableOutput('sysinfo')),
                           br(),
                           verbatimTextOutput('which_python'),
                           verbatimTextOutput('python_version'),
                           verbatimTextOutput('ret_env_var'),
                           verbatimTextOutput('venv_root')
                  )
      )
    )
  )
)

# End of ui.R
